services:
  db:
    build:
      context: ./db
    container_name: docker-crud-db
    env_file:
      - ./db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_manager -d task_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend-network

  app:
    build:
      context: ./app
    container_name: docker-crud-app
    env_file:
      - ./app.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
